version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/parmesan/src:ro
      - build:/parmesan/build
      - cargo:/usr/local/cargo
      - data:/data
    ports:
    - 1234:1234
    #command: ["rsync","-r","-u","/parmesan/src/","/parmesan/build/"]
volumes:
  build:
  cargo:
  data: